[project]
name = "cost0903-github-io"
version = "0.1.0"
description = "My Personal Blog"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.1",
]
